name: Build

on:
  push:
    branches:
      - "main"
    paths:
      - "**"
      - "!**.md"
  pull_request:

jobs:
  build:
    name: Test building
    strategy:
      matrix:
        os: [ubuntu-latest]
        dotnet: [6.0.100]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # http://man7.org/linux/man-pages/man1/date.1.html
      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
        shell: bash
      - name: Cache CSVs
        uses: actions/cache@v2
        with:
          path: |
            ./sde-static
          # We want to cache the files for a day
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}
      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: |
            ./packages
            ./paket-files
          key: ${{ runner.os }}-${{ hashFiles('**/paket.lock') }}
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Download CSVs
        run: ./download_csv.sh
      - name: Build
        run: dotnet run build
      - name: Run tests
        run: dotnet run test
